# Site settings
title: Denisse Graphic Designer Portfolio
description: A blog about lorem ipsum dolor sit amet
baseurl: "/particle" # the subpath of your site, e.g. /blog/
url: "https://takeshidead.github.io/particle/" # the base hostname & protocol for your site
# User settings
username: Denisse Graphic Designer
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Graphic Designer
email: denisse@maakako.com
twitter_username: lorem_ipsum
github_username:  Takeshidead
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
